name: Test

on: [push]
    # schedule:
    #     - cron: '0 1 1 * *'
    # workflow_dispatch:

jobs:
    BlackDuck-Scan:
        runs-on: ubuntu-latest
        env:
            projects: ("frontend" "backend" "controller" "mt")
        steps:
          - name: Check out repository code
            uses: actions/checkout@v2

          - name: abc
            run: |
                for e in ${projects[*]}; do
                    echo 1
                    echo $e
                done
