name: Test

jobs:
    BlackDuck Scan:
        runs-on: ubuntu-latest
        env:
            projects: ("frontend" "backend")
        steps:
          - name: Check out repository code
            uses: actions/checkout@v2

            name: abc
            run: |
                echo 123
